version: '3.9'
services:
  database:
    image: postgres:13
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    container_name: database-transcendence
    networks:
      - transcendence
    restart: unless-stopped
    env_file:
      - .env

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
      - 5555:5555
    env_file:
      - .env
    container_name: backend-transcendence
    volumes:
      - ./backend:/app/
      - /app/node_modules
    networks:
      - transcendence
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: frontend-transcendence
    env_file:
      - .env
    volumes:
      - ./frontend:/app/
      - /app/node_modules
    networks:
      - transcendence
    depends_on:
      - backend
    restart: unless-stopped

networks:
  transcendence: