version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    env_file:
      - .env
    # depends_on:
    #   database:
    #     condition: service_healthy
    container_name: backend-transcendence
    volumes:
      - ./backend:/app/
      - /app/node_modules
    restart: unless-stopped

  database:
    image: postgres:13
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    container_name: database-transcendence
    restart: unless-stopped
    env_file:
      - backend/.env
#     networks:
#       - freecodecamp
# networks:
#   freecodecamp: