version: '3.9'
services:
  backend:
    build: ./nest_js_course
    ports:
      - 3000
    container_name: backend-transcendence
    volumes: #remove when development is finished
      - ./nest_js_course/src:/usr/src/app/backend/src
    restart: unless-stopped